import { registerRule } from '../validate.js';
import { NoUnknownElement } from './no-unknown-element.js';
import { NoUnknownAttr } from './no-unknown-attr.js';
import { NoUnknownAttrValue } from './no-unknown-attr-value.js';
import { NoUnknownEvent } from './no-unknown-event.js';
import { NoUnknownSlot } from './no-unknown-slot.js';
import { NoUnknownCommand } from './no-unknown-command.js';
import { NoUnknownCSSPart } from './no-unknown-css-part.js';
import { NoUnknownCSSCustomProperty } from './no-unknown-css-custom-property.js';
import { NoUnknownStyleValue } from './no-unknown-style-value.js';
import { NoUnknownCustomAttrValue } from './no-unknown-custom-attr-value.js';
import { NoDeprecatedElement } from './no-deprecated-element.js';
import { NoDeprecatedAttr } from './no-deprecated-attr.js';
import { NoDeprecatedEvent } from './no-deprecated-event.js';
import { NoDeprecatedSlot } from './no-deprecated-slot.js';
import { NoDeprecatedCommand } from './no-deprecated-command.js';
import { NoBooleanAttrValue } from './no-boolean-attr-value.js';
import { NoMissingRequiredChild } from './no-missing-required-child.js';
import { NoMissingSiblingBinding } from './no-missing-sibling-binding.js';

registerRule(new NoUnknownElement());
registerRule(new NoUnknownAttr());
registerRule(new NoUnknownAttrValue());
registerRule(new NoUnknownEvent());
registerRule(new NoUnknownSlot());
registerRule(new NoUnknownCommand());
registerRule(new NoUnknownCSSPart());
registerRule(new NoUnknownCSSCustomProperty());
registerRule(new NoUnknownStyleValue());
registerRule(new NoUnknownCustomAttrValue());
registerRule(new NoDeprecatedElement());
registerRule(new NoDeprecatedAttr());
registerRule(new NoDeprecatedEvent());
registerRule(new NoDeprecatedSlot());
registerRule(new NoDeprecatedCommand());
registerRule(new NoBooleanAttrValue());
registerRule(new NoMissingRequiredChild());
registerRule(new NoMissingSiblingBinding());
