name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install
        run: bun install

      - name: ci
        run: bun run ci

      - name: build
        run: bun run build
